--<ScriptOptions statementTerminator=";"/>

CREATE TABLE vote (
	QAID BIGINT NOT NULL,
	VTYPE INT NOT NULL,
	UID BIGINT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE comment_zh (
	COID BIGINT NOT NULL,
	QID BIGINT NOT NULL,
	CTIME TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	COMMENT TINYTEXT NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	PRIMARY KEY (COID)
) ENGINE=InnoDB;

CREATE TABLE vote_en (
	VID BIGINT NOT NULL,
	QAID BIGINT NOT NULL,
	VTYPE INT NOT NULL,
	COMMENT VARCHAR(1000) NOT NULL,
	UID BIGINT NOT NULL,
	PRIMARY KEY (VID)
) ENGINE=InnoDB;

CREATE TABLE todo (
	TID BIGINT NOT NULL,
	TODO VARCHAR(1000) NOT NULL,
	NOTE TINYTEXT NOT NULL,
	TTIME TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	TTYPE CHAR(100) DEFAULT 0 NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	PRIORITY CHAR(10) DEFAULT 0 NOT NULL,
	STATUS CHAR(10) DEFAULT 0 NOT NULL,
	DEADLINE TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
	PRIMARY KEY (TID)
) ENGINE=InnoDB;

CREATE TABLE answer_en (
	AID BIGINT NOT NULL,
	QID BIGINT NOT NULL,
	atime TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	ANSWER MEDIUMTEXT NOT NULL,
	RATE INT DEFAULT 0 NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	isanswer CHAR(5) DEFAULT 0,
	PRIMARY KEY (AID)
) ENGINE=InnoDB;

CREATE TABLE question_en (
	QID BIGINT NOT NULL,
	PID BIGINT DEFAULT 0,
	CID BIGINT DEFAULT 0,
	QUESTION VARCHAR(400) NOT NULL,
	RATE INT DEFAULT 0 NOT NULL,
	ANSWERCNT INT DEFAULT 0 NOT NULL,
	TAG VARCHAR(100),
	UID BIGINT DEFAULT 0 NOT NULL,
	qtime TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	DESCRIPTION TEXT,
	STATUS CHAR(10) DEFAULT 0 NOT NULL,
	PRIMARY KEY (QID)
) ENGINE=InnoDB;

CREATE TABLE question_zh (
	QID BIGINT NOT NULL,
	PID BIGINT DEFAULT 0,
	CID BIGINT DEFAULT 0,
	QUESTION VARCHAR(400) NOT NULL,
	RATE INT DEFAULT 0 NOT NULL,
	ANSWERCNT INT DEFAULT 0 NOT NULL,
	TAG VARCHAR(100),
	UID BIGINT DEFAULT 0 NOT NULL,
	qtime TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	DESCRIPTION TEXT,
	STATUS CHAR(10) DEFAULT 0 NOT NULL,
	PRIMARY KEY (QID)
) ENGINE=InnoDB;

CREATE TABLE category_zh (
	CID BIGINT NOT NULL,
	PID BIGINT DEFAULT 0 NOT NULL,
	CATNAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (CID)
) ENGINE=InnoDB;

CREATE TABLE vote_zh (
	VID BIGINT NOT NULL,
	QAID BIGINT NOT NULL,
	VTYPE INT NOT NULL,
	COMMENT VARCHAR(1000) NOT NULL,
	UID BIGINT NOT NULL,
	PRIMARY KEY (VID)
) ENGINE=InnoDB;

CREATE TABLE users (
	UID BIGINT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	PASSWD VARCHAR(50) NOT NULL,
	CREDIT INT DEFAULT 0 NOT NULL,
	REPUTATION INT DEFAULT 0 NOT NULL,
	REGTIME TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	SKILL VARCHAR(200),
	STATUS CHAR(10) DEFAULT 0 NOT NULL,
	PRIMARY KEY (UID)
) ENGINE=InnoDB;

CREATE TABLE answer_zh (
	AID BIGINT NOT NULL,
	QID BIGINT NOT NULL,
	atime TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	ANSWER MEDIUMTEXT NOT NULL,
	RATE INT DEFAULT 0 NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	isanswer CHAR(5) DEFAULT 0,
	PRIMARY KEY (AID)
) ENGINE=InnoDB;

CREATE TABLE category_en (
	CID BIGINT NOT NULL,
	PID BIGINT DEFAULT 0 NOT NULL,
	CATNAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (CID)
) ENGINE=InnoDB;

CREATE TABLE comment_en (
	COID BIGINT NOT NULL,
	QID BIGINT NOT NULL,
	ctime TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	COMMENT TINYTEXT NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	PRIMARY KEY (COID)
) ENGINE=InnoDB;


