alter table users add column REFRESHTOKEN  VARCHAR(200);

DROP TABLE users;
CREATE TABLE users (
	UID BIGINT NOT NULL AUTO_INCREMENT,
	OPENID VARCHAR(100),
	NAME VARCHAR(100) NOT NULL,
	TITLE VARCHAR(500),
	PROFILE VARCHAR(1000),
	EMAIL VARCHAR(40) NOT NULL,
	PASSWD VARCHAR(200) NOT NULL,
	REFRESHTOKEN  VARCHAR(200),
	CREDIT INT DEFAULT 0 NOT NULL,
	REPUTATION INT DEFAULT 0 NOT NULL,
	SKILL VARCHAR(200),
	STATUS CHAR(10) DEFAULT 0 NOT NULL,
	REGTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	RESUME MEDIUMTEXT,
	PRIMARY KEY (UID)
) ENGINE=InnoDB CHARACTER SET=utf8;


CREATE TABLE category_zh (
	CID BIGINT NOT NULL AUTO_INCREMENT,
	PID BIGINT DEFAULT 0 NOT NULL,
	CATNAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(1000),
	RATE CHAR(10) DEFAULT 0,
	PRIMARY KEY (CID)
) ENGINE=InnoDB CHARACTER SET=utf8;

CREATE TABLE category_en (
	CID BIGINT NOT NULL AUTO_INCREMENT,
	PID BIGINT DEFAULT 0 NOT NULL,
	CATNAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(1000),
	RATE CHAR(10) DEFAULT 0,
	PRIMARY KEY (CID)
) ENGINE=InnoDB;

DROP TABLE question_en;
CREATE TABLE question_en (
	QID BIGINT NOT NULL AUTO_INCREMENT,
	PID BIGINT DEFAULT 0,
	CID BIGINT DEFAULT 0,
	QUESTION VARCHAR(400) NOT NULL,
	RATE INT DEFAULT 0 NOT NULL,
	ANSWERCNT INT DEFAULT 0 NOT NULL,
	TAG VARCHAR(100),
	UID BIGINT DEFAULT 0 NOT NULL,
	DESCRIPTION TEXT,
	STATUS CHAR(10) DEFAULT 0 NOT NULL,
	qtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (QID)
) ENGINE=InnoDB;


DROP TABLE question_zh;
CREATE TABLE question_zh (
	QID BIGINT NOT NULL AUTO_INCREMENT,
	PID BIGINT DEFAULT 0,
	CID BIGINT DEFAULT 0,
	QUESTION VARCHAR(400) NOT NULL,
	RATE INT DEFAULT 0 NOT NULL,
	ANSWERCNT INT DEFAULT 0 NOT NULL,
	TAG VARCHAR(100),
	UID BIGINT DEFAULT 0 NOT NULL,
	DESCRIPTION TEXT,
	STATUS CHAR(10) DEFAULT 0 NOT NULL,
	qtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (QID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE answer_zh
CREATE TABLE answer_zh (
	AID BIGINT NOT NULL AUTO_INCREMENT,
	QID BIGINT NOT NULL,
	ANSWER MEDIUMTEXT NOT NULL,
	RATE INT DEFAULT 0 NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	atime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	isanswer CHAR(5) DEFAULT 0,
	PRIMARY KEY (AID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE answer_en;
CREATE TABLE answer_en (
	AID BIGINT NOT NULL AUTO_INCREMENT,
	QID BIGINT NOT NULL,
	ANSWER MEDIUMTEXT NOT NULL,
	RATE INT DEFAULT 0 NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	atime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	isanswer CHAR(5) DEFAULT 0,
	PRIMARY KEY (AID)
) ENGINE=InnoDB;

DROP TABLE comment_en;
CREATE TABLE comment_en (
	COID BIGINT NOT NULL AUTO_INCREMENT,
	QID BIGINT NOT NULL,
	COMMENT MEDIUMTEXT NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (COID)
) ENGINE=InnoDB;

DROP TABLE comment_zh;
CREATE TABLE comment_zh (
	COID BIGINT NOT NULL AUTO_INCREMENT,
	QID BIGINT NOT NULL,
	COMMENT MEDIUMTEXT NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (COID)
) ENGINE=InnoDB CHARACTER SET=utf8;


DROP TABLE vote;
CREATE TABLE vote (
	VID BIGINT NOT NULL,
	VTYPE INT NOT NULL,--1 ISSUE, 2 proposal
	UID BIGINT NOT NULL,
	NVOTE CHAR(5),
	UNIQUE(VID,VTYPE,UID)
) ENGINE=InnoDB;


DROP TABLE todo;
CREATE TABLE todo (
	TID BIGINT NOT NULL AUTO_INCREMENT,
	TODO VARCHAR(1000) NOT NULL,
	NOTE TEXT NOT NULL,
	TTYPE CHAR(10) DEFAULT 0 NOT NULL,
	UID BIGINT DEFAULT 0 NOT NULL,
	PRIORITY CHAR(10) DEFAULT 0 NOT NULL,
	STATUS CHAR(10) DEFAULT 0 NOT NULL,
	ttime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deadline TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL,
	PRIMARY KEY (TID)
) ENGINE=InnoDB CHARACTER SET=utf8;


--2014/4/13
DROP TABLE userlog_en;
CREATE TABLE userlog_en(
	LID BIGINT NOT NULL AUTO_INCREMENT,
	UID BIGINT DEFAULT 0 NOT NULL,
	LTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	TAG VARCHAR(100),
	SUBJECT VARCHAR(1000) NOT NULL,
	ULOG MEDIUMTEXT NOT NULL,
	STATUS CHAR(10) DEFAULT 0,
	LTYPE CHAR(5) DEFAULT 0,
	PRIMARY KEY (LID)
)ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE userlog_zh;
CREATE TABLE userlog_zh(
	LID BIGINT NOT NULL AUTO_INCREMENT,
	UID BIGINT DEFAULT 0 NOT NULL,
	LTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	TAG VARCHAR(100),
	SUBJECT VARCHAR(1000) NOT NULL,
	ULOG MEDIUMTEXT NOT NULL,
	STATUS CHAR(10) DEFAULT 0,
	LTYPE CHAR(5) DEFAULT 0,
	PRIMARY KEY (LID)
)ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE tag_en;
CREATE TABLE tag_en(
	id BIGINT NOT NULL AUTO_INCREMENT,
	name varchar(50),
	description varchar(100),
	cnt_use bigint,
	cnt_follow bigint,
	cid bigint,
	primary key (id)
)ENGINE=InnoDB;

DROP TABLE tag_zh;
CREATE TABLE tag_zh(
	id BIGINT NOT NULL AUTO_INCREMENT,
	name varchar(50),
	description varchar(200),
	cnt_use bigint,
	cnt_follow bigint,
	cid bigint,
	primary key (id)
)ENGINE=InnoDB CHARACTER SET=utf8;

--2014-5/25
DROP TABLE activity_en;
CREATE TABLE activity_en (
	AID BIGINT NOT NULL AUTO_INCREMENT,
	SUBJECT VARCHAR(1000) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	ATYPE CHAR(10) DEFAULT 0 NOT NULL,
	LOCATION VARCHAR(1000) NOT NULL,
	ASTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	AETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	COST DOUBLE,
	ATTCNT INT,
	UID BIGINT NOT NULL,
	PRIMARY KEY (AID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE activity_zh;
CREATE TABLE activity_zh (
	AID BIGINT NOT NULL AUTO_INCREMENT,
	SUBJECT VARCHAR(1000) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	ATYPE CHAR(10) DEFAULT 0 NOT NULL,
	LOCATION VARCHAR(1000) NOT NULL,
	ASTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	AETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	COST DOUBLE,
	ATTCNT INT,
	UID BIGINT NOT NULL,
	PRIMARY KEY (AID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE follow;
CREATE TABLE follow(
	UID BIGINT NOT NULL,
	FID BIGINT NOT NULL,
	LANG VARCHAR(6),
	FTYPE INT, -- 1 USER,2 CAT,3 TAG,4 QUESTION
	ALIAS VARCHAR(50)	
)ENGINE=InnoDB CHARACTER SET=utf8;

--2014/10/7
DROP TABLE ITEM;
CREATE TABLE ITEM(
	CID BIGINT DEFAULT 0, 
	ITEMID BIGINT NOT NULL AUTO_INCREMENT,
	ITEM VARCHAR(100) NOT NULL,
	TAGS VARCHAR(200),
	FUNCTIONS VARCHAR(1000),
	ADVANTAGES TEXT,
	DISADVANTAS TEXT,
	ADDTION TEXT,
	PRIMARY KEY (ITEMID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE FUNCTION;
CREATE TABLE FUNCTION(
	CID BIGINT DEFAULT 0,
	FUNCID BIGINT NOT NULL AUTO_INCREMENT,
	FUNCTION VARCHAR(1000) NOT NULL,
	PRIMARY KEY (FUNCID)
) ENGINE=InnoDB CHARACTER SET=utf8;



--2014-11-2
