DROP TABLE CASES;
CREATE TABLE CASES(
	CASEID BIGINT NOT NULL AUTO_INCREMENT,
	SUBJECT VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT,
	TAG VARCHAR(100),
	PHASEID INT NOT NULL,
	STARTDATE DATE,
	ENDDATE DATE,
	STATUS CHAR(5),
	UID BIGINT NOT NULL,
	PRIMARY KEY (CASEID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE PHASE;
CREATE TABLE PHASE(
	PHASEID INT NOT NULL,
	CASEID BIGINT NOT NULL,
	PHASE VARCHAR(100),
	NOTE TEXT,
	STARTDATE DATE,
	ENDDATE DATE,
	TAG VARCHAR(100),
	PRIMARY KEY (CASEID,PHASEID)
)ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE ITEM;
CREATE TABLE ITEM(
	ITEMID BIGINT NOT NULL AUTO_INCREMENT,
	ITEM VARCHAR(100) NOT NULL,
	NOTE TEXT,
	DOTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PHASEID INT NOT NULL,
	CASEID BIGINT NOT NULL,
	PRIMARY KEY (ITEMID)
)ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE COMMENT;
CREATE TABLE COMMENT(
	COMMENTID BIGINT NOT NULL AUTO_INCREMENT,
	COMMENT TEXT NOT NULL,
	CASEID BIGINT NOT NULL,
	PHASEID BIGINT NOT NULL,
	CREATETIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UID BIGINT,
	PRIMARY KEY (COMMENTID)
)ENGINE=InnoDB CHARACTER SET=utf8;