UPDATE ITEM SET STATUS=1

----upgrade ----
ALTER TABLE ITEM ADD COLUMN OWNER BIGINT
ALTER TABLE ITEM MODIFY COLUMN DOTIME TIMESTAMP
ALTER TABLE COMMENT MODIFY COLUMN PHASEID BIGINT
-------------------init -----------------
DROP TABLE CASES;
CREATE TABLE CASES(
	CASEID BIGINT NOT NULL AUTO_INCREMENT,
	SUBJECT VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT,
	TAG VARCHAR(100),
	PHASEID INT NOT NULL,
	STARTDATE TIMESTAMP,
	ENDDATE TIMESTAMP,
	STATUS CHAR(5),
	CTYPE CHAR(5),
	ISOPEN BOOLEAN NOT NULL,
	UID BIGINT NOT NULL,
	PRIMARY KEY (CASEID)
) ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE PHASE;
CREATE TABLE PHASE(
	PHASEID INT NOT NULL,
	CASEID BIGINT NOT NULL,
	PHASE VARCHAR(100),
	NOTE TEXT,
	STARTDATE TIMESTAMP,
	ENDDATE TIMESTAMP,
	TAG VARCHAR(100),
	PRIMARY KEY (CASEID,PHASEID)
)ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE ITEM;
CREATE TABLE ITEM(
	ITEMID BIGINT NOT NULL AUTO_INCREMENT,
	ITEM VARCHAR(100) NOT NULL,
	NOTE TEXT,
	OWNER BIGINT,
	DOTIME TIMESTAMP,
	PHASEID INT NOT NULL,
	CASEID BIGINT NOT NULL,
	STATUS TINYINT,
	PRIMARY KEY (ITEMID)
)ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE COMMENT;
CREATE TABLE COMMENT(
	COMMENTID BIGINT NOT NULL AUTO_INCREMENT,
	COMMENT TEXT NOT NULL,
	CASEID BIGINT NOT NULL,
	PHASEID BIGINT,
	CREATETIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UID BIGINT,
	PRIMARY KEY (COMMENTID)
)ENGINE=InnoDB CHARACTER SET=utf8;

DROP TABLE TAG;
CREATE TABLE TAG(
	TAG VARCHAR(100),
	COUNT INT,
	DESCRIPTION TEXT
) ENGINE=InnoDB CHARACTER SET=utf8;

--2014/11/17
DROP TABLE QUESTION;
CREATE TABLE QUESTION(
	QUESID BIGINT NOT NULL AUTO_INCREMENT,
	SUBJECT VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT,
	ISANSWERED BOOLEAN NOT NULL,
	CASEID BIGINT NOT NULL,
	ASKWHO BIGINT,
	PRIMARY KEY (QUESID)
	
)ENGINE=InnoDB CHARACTER SET=utf8;

--2014/11/18
DROP TABLE COLLABORATION;
CREATE TABLE COLLABORATION(
	CASEID BIGINT NOT NULL,
	UID BIGINT NOT NULL,
	ACCESS TINYINT
)ENGINE=InnoDB;
